CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n

# HID battery reporting over USB
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_USB_BOOT=n

CONFIG_ZMK_USB_LOGGING=y
CONFIG_LOG_MODE_IMMEDIATE=n
CONFIG_ZMK_LOG_LEVEL_DBG=y